#!/usr/bin/env python3
"""
C++ code generator for state-change fixes from policy YAML.

Generates .cpp and .h files from policy YAML using Jinja2 templates.
"""

from pathlib import Path
from jinja2 import Environment, FileSystemLoader
from policy_parser import PolicyParser


class FixCodeGenerator:
    """Generate C++ fix code from policy YAML."""

    def __init__(self, policy_yaml: Path, output_dir: Path):
        self.policy_yaml = policy_yaml
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Parse policy
        self.parser = PolicyParser(policy_yaml)
        self.policy = self.parser.parse()

        # Setup Jinja2
        template_dir = Path(__file__).parent / 'templates'
        self.env = Environment(
            loader=FileSystemLoader(str(template_dir)),
            trim_blocks=True,
            lstrip_blocks=True
        )

    def generate(self):
        """Generate both .cpp and .h files."""
        print(f"Generating C++ code from {self.policy_yaml.name}...")

        # Generate filenames
        base_name = self.parser.get_cpp_filename()
        cpp_file = self.output_dir / f"{base_name}.cpp"
        h_file = self.output_dir / f"{base_name}.h"

        # Generate .cpp
        self._generate_cpp(cpp_file)

        # Generate .h
        self._generate_header(h_file)

        print(f"  ✓ Generated {cpp_file}")
        print(f"  ✓ Generated {h_file}")

        return cpp_file, h_file

    def _generate_cpp(self, output_path: Path):
        """Generate .cpp file."""
        # Load template
        template = self.env.get_template('fix_check_and_change.cpp.j2')

        # Prepare template context
        context = {
            'policy': self.policy,
            'metadata': self.policy['metadata'],
            'parameters': self.policy['parameters'],
            'rules': self.policy['rules'],
            'advanced': self.policy.get('advanced', {}),
            'fix_class_name': self.parser.get_fix_name(),
            'base_filename': self.parser.get_cpp_filename()
        }

        # Render template
        cpp_code = template.render(**context)

        # Write complete .cpp file (with includes, constructor, etc.)
        full_cpp = self._wrap_cpp_code(cpp_code)

        with open(output_path, 'w') as f:
            f.write(full_cpp)

    def _wrap_cpp_code(self, check_and_change_code: str) -> str:
        """Wrap generated check_and_change code with boilerplate."""
        problem = self.policy['metadata'].get('problem', 'generic')
        policy_name = self.policy['metadata']['name']
        fix_class = self.parser.get_fix_name()
        base_name = self.parser.get_cpp_filename()

        cpp_template = f'''/* -*- c++ -*- ----------------------------------------------------------
   Auto-generated LAMMPS fix from policy YAML
   Policy: {policy_name}
   Problem: {problem}
   Generated by: framework/generators/fix_codegen.py
------------------------------------------------------------------------- */

#include "{base_name}.h"

#include "atom.h"
#include "comm.h"
#include "domain.h"
#include "error.h"
#include "force.h"
#include "group.h"
#include "memory.h"
#include "modify.h"
#include "neighbor.h"
#include "neigh_list.h"
#include "random_park.h"
#include "update.h"

#include <mpi.h>
#include <cmath>
#include <cstring>
#include <map>
#include <set>
#include <vector>

using namespace LAMMPS_NS;
using namespace FixConst;

/* ---------------------------------------------------------------------- */

{fix_class}::{fix_class}(LAMMPS *lmp, int narg, char **arg) :
    Fix(lmp, narg, arg), last_change(nullptr), cooldown_duration(nullptr),
    effective_type(nullptr), prev_coord(nullptr), contact_timer(nullptr)
{{
  if (narg < 8) error->all(FLERR, "Illegal fix {base_name} command");

  check_every = {self.policy['parameters']['check_every']};
  cooldown_steps = {self.policy['parameters']['cooldown_steps']};
  probability = {self.policy['parameters']['probability']};
  cutoff = {self.policy['parameters']['cutoff']};
  hysteresis_threshold = {self.policy['parameters']['hysteresis_threshold']};

  group_patches = group->find(arg[7]);
  if (group_patches < 0) error->all(FLERR, "Fix {base_name} group_patches not found");

  peratom_flag = 1;
  size_peratom_cols = 0;
  peratom_freq = 1;
  restart_global = 1;
  restart_peratom = 1;
  comm_forward = 4;

  next_check = update->ntimestep + check_every;
  nchanges = 0;
  nattempts = 0;
  seed = 12345;
  max_changes_per_step = {self.policy['parameters'].get('max_changes_per_step', 1)};

  nconfident_contacts = 0;
  ntrigger_attempts = 0;
  ncooldown_blocked = 0;

  scalar_flag = 1;
  global_freq = 1;
  extscalar = 0;

  grow_arrays(atom->nmax);

  int nlocal = atom->nlocal;
  for (int i = 0; i < nlocal; i++) {{
    effective_type[i] = atom->type[i];
    last_change[i] = -1;
    prev_coord[i] = 0.0;
    contact_timer[i] = 0;
  }}
}}

{fix_class}::~{fix_class}()
{{
  memory->destroy(last_change);
  memory->destroy(cooldown_duration);
  memory->destroy(effective_type);
  memory->destroy(prev_coord);
  memory->destroy(contact_timer);
}}

int {fix_class}::setmask()
{{
  int mask = 0;
  mask |= POST_FORCE;
  mask |= END_OF_STEP;
  return mask;
}}

void {fix_class}::init()
{{
  if (next_check < update->ntimestep) next_check = update->ntimestep + check_every;

  if (atom->nmax > 0) {{
    grow_arrays(atom->nmax);
  }}

  int *type = atom->type;
  int *mask = atom->mask;
  int nlocal = atom->nlocal;

  if (group_patches < 0 || group_patches >= group->ngroup) {{
    error->all(FLERR, "Fix {base_name}: Invalid group_patches in init()");
  }}

  int patch_mask = group->bitmask[group_patches];

  for (int i = 0; i < nlocal; i++) {{
    if (mask[i] & groupbit) {{
      if (mask[i] & patch_mask) {{
        if (type[i] == 2 || type[i] == 3 || type[i] == 4 || type[i] == 5) {{
          if (type[i] == 2) {{
            effective_type[i] = 1;
          }} else {{
            effective_type[i] = type[i];
          }}
        }} else {{
          effective_type[i] = 1;
        }}
        last_change[i] = -1;
        cooldown_duration[i] = cooldown_steps;
        prev_coord[i] = 0.0;
        contact_timer[i] = 0;
      }} else {{
        effective_type[i] = type[i];
        last_change[i] = -1;
        cooldown_duration[i] = cooldown_steps;
        prev_coord[i] = 0.0;
        contact_timer[i] = 0;
      }}
    }}
  }}
}}

void {fix_class}::post_force(int /*vflag*/)
{{
  if (update->ntimestep < next_check) return;

  next_check = update->ntimestep + check_every;
  nchanges = 0;
  nattempts = 0;

  check_and_change();
}}

void {fix_class}::end_of_step()
{{
  if (nchanges > 0) {{
    update_atom_types();
  }}
}}

double {fix_class}::get_coordination(int i, int effective_patch_type)
{{
  if (i < 0 || i >= atom->nmax) return 0.0;
  if (!domain || !atom->x || !atom->x[i]) return 0.0;

  int *type = atom->type;
  int *mask = atom->mask;
  int *molecule = atom->molecule;
  if (!type || !mask || !molecule) return 0.0;

  int my_mol = molecule[i];
  int nlocal = atom->nlocal;
  double *prd = domain->prd;

  if (!prd) return 0.0;

  double coord = 0.0;
  double cutoffsq = cutoff * cutoff;

  int lammps_target_type;
  if (effective_patch_type == 1) {{
    lammps_target_type = 2;
  }} else {{
    lammps_target_type = effective_patch_type;
  }}

  for (int j = 0; j < nlocal; j++) {{
    if (i == j) continue;
    if (molecule[j] == my_mol) continue;
    if (!(mask[j] & group->bitmask[group_patches])) continue;
    if (type[j] != lammps_target_type) continue;

    if (j >= atom->nmax || !atom->x[j]) continue;

    double dx = atom->x[j][0] - atom->x[i][0];
    double dy = atom->x[j][1] - atom->x[i][1];
    double dz = atom->x[j][2] - atom->x[i][2];

    if (prd[0] > 0.0) dx -= prd[0] * std::round(dx / prd[0]);
    if (prd[1] > 0.0) dy -= prd[1] * std::round(dy / prd[1]);
    if (prd[2] > 0.0) dz -= prd[2] * std::round(dz / prd[2]);

    double rsq = dx*dx + dy*dy + dz*dz;
    if (rsq < cutoffsq) {{
      coord += 1.0;
    }}
  }}

  return coord;
}}

{check_and_change_code}

void {fix_class}::update_atom_types()
{{
  bigint natoms_before = atom->natoms;
  comm->forward_comm(this);

  int *type = atom->type;
  int *mask = atom->mask;
  int *molecule = atom->molecule;
  int nlocal = atom->nlocal;

  for (int i = 0; i < nlocal; i++) {{
    if (!(mask[i] & groupbit)) continue;
    if (!(mask[i] & group->bitmask[group_patches])) continue;
    if (type[i] != 2 && type[i] != 3 && type[i] != 4 && type[i] != 5) continue;

    int eff = effective_type[i];
    int new_lammps_type;

    if (eff == 1) {{
      new_lammps_type = 2;
    }} else if (eff == 3 || eff == 4 || eff == 5) {{
      new_lammps_type = eff;
    }} else {{
      continue;
    }}

    if (type[i] != new_lammps_type) {{
      type[i] = new_lammps_type;
    }}
  }}

  if (atom->natoms != natoms_before) {{
    error->all(FLERR, "Fix {base_name}: Atom count changed during type update");
  }}

  comm->forward_comm();

  if (atom->natoms != natoms_before) {{
    error->all(FLERR, "Fix {base_name}: Atom count changed after communication");
  }}

  neighbor->decide();
}}

double {fix_class}::compute_scalar()
{{
  return static_cast<double>(nchanges);
}}

void {fix_class}::grow_arrays(int nmax)
{{
  memory->grow(last_change, nmax, "{base_name}:last_change");
  memory->grow(cooldown_duration, nmax, "{base_name}:cooldown_duration");
  memory->grow(effective_type, nmax, "{base_name}:effective_type");
  memory->grow(prev_coord, nmax, "{base_name}:prev_coord");
  memory->grow(contact_timer, nmax, "{base_name}:contact_timer");
}}

void {fix_class}::copy_arrays(int i, int j, int /*delflag*/)
{{
  last_change[j] = last_change[i];
  cooldown_duration[j] = cooldown_duration[i];
  effective_type[j] = effective_type[i];
  prev_coord[j] = prev_coord[i];
  contact_timer[j] = contact_timer[i];
}}

int {fix_class}::pack_forward_comm(int n, int *list, double *buf, int pbc_flag, int *pbc)
{{
  int i, j, m = 0;

  for (i = 0; i < n; i++) {{
    j = list[i];
    buf[m++] = static_cast<double>(last_change[j]);
    buf[m++] = static_cast<double>(cooldown_duration[j]);
    buf[m++] = static_cast<double>(effective_type[j]);
    buf[m++] = prev_coord[j];
  }}

  return m;
}}

void {fix_class}::unpack_forward_comm(int n, int first, double *buf)
{{
  int i, m = 0, last = first + n;

  for (i = first; i < last; i++) {{
    last_change[i] = static_cast<int>(buf[m++]);
    cooldown_duration[i] = static_cast<int>(buf[m++]);
    effective_type[i] = static_cast<int>(buf[m++]);
    prev_coord[i] = buf[m++];
  }}
}}
'''
        return cpp_template

    def _generate_header(self, output_path: Path):
        """Generate .h header file."""
        fix_class = self.parser.get_fix_name()
        base_name = self.parser.get_cpp_filename()
        problem = self.policy['metadata'].get('problem', 'generic')
        guard = f"LMP_FIX_STATE_CHANGE_{problem.upper()}_{self.policy['metadata']['name'].upper()}_H"

        header = f'''/* -*- c++ -*- ----------------------------------------------------------
   Auto-generated LAMMPS fix header from policy YAML
   Policy: {self.policy['metadata']['name']}
   Problem: {problem}
------------------------------------------------------------------------- */

#ifdef FIX_CLASS
// clang-format off
 FixStyle(state/change/{problem}/{self.policy['metadata']['name']},{fix_class});
// clang-format on
#else

#ifndef {guard}
#define {guard}

#include "fix.h"

namespace LAMMPS_NS {{

class RanPark;

class {fix_class} : public Fix {{
 public:
  {fix_class}(class LAMMPS *, int, char **);
  ~{fix_class}() override;
  int setmask() override;
  void init() override;
  void post_force(int) override;
  void end_of_step() override;
  double compute_scalar() override;
  int pack_forward_comm(int, int *, double *, int, int *) override;
  void unpack_forward_comm(int, int, double *) override;
  void grow_arrays(int) override;
  void copy_arrays(int, int, int) override;

 private:
  int check_every;
  int cooldown_steps;
  double probability;
  double cutoff;
  int group_patches;
  int hysteresis_threshold;
  int max_changes_per_step;

  int *last_change;
  int *cooldown_duration;
  int *effective_type;
  double *prev_coord;
  int *contact_timer;

  bigint next_check;
  int nchanges;
  int nattempts;
  int seed;

  int nconfident_contacts;
  int ntrigger_attempts;
  int ncooldown_blocked;

  void check_and_change();
  void update_atom_types();
  double get_coordination(int, int);
}};

}}    // namespace LAMMPS_NS

#endif
#endif
'''
        with open(output_path, 'w') as f:
            f.write(header)


def main():
    """Test the code generator."""
    import sys
    if len(sys.argv) < 2:
        print("Usage: python fix_codegen.py <policy.yaml> [output_dir]")
        sys.exit(1)

    policy_yaml = Path(sys.argv[1])
    output_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path('generated')

    generator = FixCodeGenerator(policy_yaml, output_dir)
    cpp_file, h_file = generator.generate()

    print(f"\nGenerated files:")
    print(f"  {cpp_file}")
    print(f"  {h_file}")
    print(f"\nTo compile:")
    print(f"  cp {output_dir}/* /path/to/lammps/src/")
    print(f"  cd /path/to/lammps/src/")
    print(f"  make mpi")


if __name__ == '__main__':
    main()
