/* -*- c++ -*- ----------------------------------------------------------
   Auto-generated LAMMPS fix from policy YAML
   Policy: avoid_same_type_octahedron
   Problem: octahedron
   Generated by: framework/generators/fix_codegen.py
------------------------------------------------------------------------- */

#include "fix_state_change_octahedron_avoid_same_type_octahedron.h"

#include "atom.h"
#include "comm.h"
#include "domain.h"
#include "error.h"
#include "force.h"
#include "group.h"
#include "memory.h"
#include "modify.h"
#include "neighbor.h"
#include "neigh_list.h"
#include "random_park.h"
#include "update.h"

#include <mpi.h>
#include <cmath>
#include <cstring>
#include <map>
#include <set>
#include <vector>

using namespace LAMMPS_NS;
using namespace FixConst;

/* ---------------------------------------------------------------------- */

FixStateChangeOctahedronAvoidSameTypeOctahedron::FixStateChangeOctahedronAvoidSameTypeOctahedron(LAMMPS *lmp, int narg, char **arg) :
    Fix(lmp, narg, arg), last_change(nullptr), cooldown_duration(nullptr),
    effective_type(nullptr), prev_coord(nullptr), contact_timer(nullptr)
{
  if (narg < 8) error->all(FLERR, "Illegal fix fix_state_change_octahedron_avoid_same_type_octahedron command");

  check_every = 100;
  cooldown_steps = 10000;
  probability = 1.0;
  cutoff = 2.5;
  hysteresis_threshold = 1000;

  group_patches = group->find(arg[7]);
  if (group_patches < 0) error->all(FLERR, "Fix fix_state_change_octahedron_avoid_same_type_octahedron group_patches not found");

  peratom_flag = 1;
  size_peratom_cols = 0;
  peratom_freq = 1;
  restart_global = 1;
  restart_peratom = 1;
  comm_forward = 4;

  next_check = update->ntimestep + check_every;
  nchanges = 0;
  nattempts = 0;
  seed = 12345;
  max_changes_per_step = 1;

  nconfident_contacts = 0;
  ntrigger_attempts = 0;
  ncooldown_blocked = 0;

  scalar_flag = 1;
  global_freq = 1;
  extscalar = 0;

  grow_arrays(atom->nmax);

  int nlocal = atom->nlocal;
  for (int i = 0; i < nlocal; i++) {
    effective_type[i] = atom->type[i];
    last_change[i] = -1;
    prev_coord[i] = 0.0;
    contact_timer[i] = 0;
  }
}

FixStateChangeOctahedronAvoidSameTypeOctahedron::~FixStateChangeOctahedronAvoidSameTypeOctahedron()
{
  memory->destroy(last_change);
  memory->destroy(cooldown_duration);
  memory->destroy(effective_type);
  memory->destroy(prev_coord);
  memory->destroy(contact_timer);
}

int FixStateChangeOctahedronAvoidSameTypeOctahedron::setmask()
{
  int mask = 0;
  mask |= POST_FORCE;
  mask |= END_OF_STEP;
  return mask;
}

void FixStateChangeOctahedronAvoidSameTypeOctahedron::init()
{
  if (next_check < update->ntimestep) next_check = update->ntimestep + check_every;

  if (atom->nmax > 0) {
    grow_arrays(atom->nmax);
  }

  int *type = atom->type;
  int *mask = atom->mask;
  int nlocal = atom->nlocal;

  if (group_patches < 0 || group_patches >= group->ngroup) {
    error->all(FLERR, "Fix fix_state_change_octahedron_avoid_same_type_octahedron: Invalid group_patches in init()");
  }

  int patch_mask = group->bitmask[group_patches];

  for (int i = 0; i < nlocal; i++) {
    if (mask[i] & groupbit) {
      if (mask[i] & patch_mask) {
        if (type[i] == 2 || type[i] == 3 || type[i] == 4 || type[i] == 5) {
          if (type[i] == 2) {
            effective_type[i] = 1;
          } else {
            effective_type[i] = type[i];
          }
        } else {
          effective_type[i] = 1;
        }
        last_change[i] = -1;
        cooldown_duration[i] = cooldown_steps;
        prev_coord[i] = 0.0;
        contact_timer[i] = 0;
      } else {
        effective_type[i] = type[i];
        last_change[i] = -1;
        cooldown_duration[i] = cooldown_steps;
        prev_coord[i] = 0.0;
        contact_timer[i] = 0;
      }
    }
  }
}

void FixStateChangeOctahedronAvoidSameTypeOctahedron::post_force(int /*vflag*/)
{
  if (update->ntimestep < next_check) return;

  next_check = update->ntimestep + check_every;
  nchanges = 0;
  nattempts = 0;

  check_and_change();
}

void FixStateChangeOctahedronAvoidSameTypeOctahedron::end_of_step()
{
  if (nchanges > 0) {
    update_atom_types();
  }
}

double FixStateChangeOctahedronAvoidSameTypeOctahedron::get_coordination(int i, int effective_patch_type)
{
  if (i < 0 || i >= atom->nmax) return 0.0;
  if (!domain || !atom->x || !atom->x[i]) return 0.0;

  int *type = atom->type;
  int *mask = atom->mask;
  int *molecule = atom->molecule;
  if (!type || !mask || !molecule) return 0.0;

  int my_mol = molecule[i];
  int nlocal = atom->nlocal;
  double *prd = domain->prd;

  if (!prd) return 0.0;

  double coord = 0.0;
  double cutoffsq = cutoff * cutoff;

  int lammps_target_type;
  if (effective_patch_type == 1) {
    lammps_target_type = 2;
  } else {
    lammps_target_type = effective_patch_type;
  }

  for (int j = 0; j < nlocal; j++) {
    if (i == j) continue;
    if (molecule[j] == my_mol) continue;
    if (!(mask[j] & group->bitmask[group_patches])) continue;
    if (type[j] != lammps_target_type) continue;

    if (j >= atom->nmax || !atom->x[j]) continue;

    double dx = atom->x[j][0] - atom->x[i][0];
    double dy = atom->x[j][1] - atom->x[i][1];
    double dz = atom->x[j][2] - atom->x[i][2];

    if (prd[0] > 0.0) dx -= prd[0] * std::round(dx / prd[0]);
    if (prd[1] > 0.0) dy -= prd[1] * std::round(dy / prd[1]);
    if (prd[2] > 0.0) dz -= prd[2] * std::round(dz / prd[2]);

    double rsq = dx*dx + dy*dy + dz*dz;
    if (rsq < cutoffsq) {
      coord += 1.0;
    }
  }

  return coord;
}

void FixStateChangeOctahedronAvoidSameTypeOctahedron::check_and_change()
{
  // CRITICAL FIX: Update ghost atoms immediately before conflict checks
  comm->forward_comm(this);

  int *type = atom->type;
  int *mask = atom->mask;
  int *molecule = atom->molecule;
  int nlocal = atom->nlocal;
  bigint timestep = update->ntimestep;

  std::map<int, int> mol_changes;

  // SCAN LOOP: Look for triggers
  for (int i = 0; i < nlocal; i++) {
    int my_seed = seed + static_cast<int>(timestep) + comm->me + molecule[i];
    RanPark random(lmp, my_seed);

    // Basic filters
    if (!(mask[i] & groupbit)) continue;
    if (!(mask[i] & group->bitmask[group_patches])) continue;
    if (type[i] != 2 && type[i] != 3 && type[i] != 4 && type[i] != 5) continue;

    // Skip if already scheduled
    if (mol_changes.find(molecule[i]) != mol_changes.end()) continue;

    // Cooldown check
    if (last_change[i] >= 0) {
        bigint steps_since_change = timestep - last_change[i];
        if (steps_since_change < cooldown_duration[i]) continue;
    }

    int my_eff_type = effective_type[i];

    // Compute coordination
    double coord_1 = get_coordination(i, 1);
    double coord_3 = get_coordination(i, 3);
    double coord_4 = get_coordination(i, 4);
    double coord_5 = get_coordination(i, 5);
    double total_coord = coord_1 + coord_3 + coord_4 + coord_5;

    bool is_attached = (total_coord >= 1.0);

    // Hysteresis logic
    if (is_attached) {
        contact_timer[i]++;
    } else {
        contact_timer[i] = 0;
    }

    bool confident = (contact_timer[i] > hysteresis_threshold);
    bool trigger_moment = (contact_timer[i] == (hysteresis_threshold + 1)) ||
                          (contact_timer[i] > hysteresis_threshold && random.uniform() < (1.0 / 50.0));

    bool should_change = false;
    int new_type = my_eff_type;

    // Rule: type1_collision
    if (my_eff_type == 1 && confident && trigger_moment) {
        bool touching_same_type_1 = (coord_1 >= 1.0);

        if (touching_same_type_1) {
            int my_mol = molecule[i];
            bool all_neighbors_lower_id = true;
            double cutoffsq = 2.5 * 2.5;

            int nall = atom->nlocal + atom->nghost;
            for (int j = 0; j < nall; j++) {
                if (j == i) continue;
                if (molecule[j] == my_mol) continue;
                if (!(mask[j] & group->bitmask[group_patches])) continue;
                if (effective_type[j] != 1) continue;

                double dx = atom->x[j][0] - atom->x[i][0];
                double dy = atom->x[j][1] - atom->x[i][1];
                double dz = atom->x[j][2] - atom->x[i][2];
                double *prd = domain->prd;
                if (prd[0] > 0.0) dx -= prd[0] * std::round(dx / prd[0]);
                if (prd[1] > 0.0) dy -= prd[1] * std::round(dy / prd[1]);
                if (prd[2] > 0.0) dz -= prd[2] * std::round(dz / prd[2]);
                double rsq = dx*dx + dy*dy + dz*dz;

                if (rsq < cutoffsq) {
                    int neighbor_mol = molecule[j];
                    if (neighbor_mol > my_mol) {
                        all_neighbors_lower_id = false;
                    }
                }
            }

            if (all_neighbors_lower_id) {
                should_change = true;
                // Pick randomly from [3, 4, 5]
                double r = random.uniform();
                if (r < 0.333333) new_type = 3;
                else if (r < 0.666666) new_type = 4;
                else new_type = 5;
                nattempts++;
                int jitter_magnitude = 10;
                int random_jitter = static_cast<int>(random.uniform() * jitter_magnitude);
                contact_timer[i] = -random_jitter;
            }
        }
    }
    // Rule: same_type_conflict
    // Reacted monomer logic (types 3/4/5)
    else if ((my_eff_type == 3 || my_eff_type == 4 || my_eff_type == 5) && confident && trigger_moment) {
        bool touching_same = false;
        if (my_eff_type == 3 && coord_3 >= 1.0) touching_same = true;
        if (my_eff_type == 4 && coord_4 >= 1.0) touching_same = true;
        if (my_eff_type == 5 && coord_5 >= 1.0) touching_same = true;

        if (touching_same) {
            bool self_in_cooldown = false;
            if (last_change[i] >= 0) {
                bigint steps_since_change = timestep - last_change[i];
                if (steps_since_change < cooldown_duration[i]) {
                    self_in_cooldown = true;
                }
            }

            if (self_in_cooldown) {
                ncooldown_blocked++;
            } else {
                int my_mol = molecule[i];
                bool should_i_change = false;
                bool found_conflict = false;
                bool all_neighbors_lower_id = true;
                double cutoffsq = 2.5 * 2.5;

                int nall = atom->nlocal + atom->nghost;
                for (int j = 0; j < nall; j++) {
                    if (j == i) continue;
                    if (molecule[j] == my_mol) continue;
                    if (!(mask[j] & group->bitmask[group_patches])) continue;
                    if (type[j] < 2 || type[j] > 5) continue;

                    int j_eff_type = effective_type[j];
                    if (j_eff_type != my_eff_type) continue;

                    double dx = atom->x[j][0] - atom->x[i][0];
                    double dy = atom->x[j][1] - atom->x[i][1];
                    double dz = atom->x[j][2] - atom->x[i][2];
                    double *prd = domain->prd;
                    if (prd[0] > 0.0) dx -= prd[0] * std::round(dx / prd[0]);
                    if (prd[1] > 0.0) dy -= prd[1] * std::round(dy / prd[1]);
                    if (prd[2] > 0.0) dz -= prd[2] * std::round(dz / prd[2]);
                    double rsq = dx*dx + dy*dy + dz*dz;

                    if (rsq < cutoffsq) {
                        found_conflict = true;
                        int neighbor_mol = molecule[j];
                        if (neighbor_mol > my_mol) {
                            all_neighbors_lower_id = false;
                        }
                    }
                }

                if (found_conflict && all_neighbors_lower_id) {
                    should_i_change = true;
                }

                if (should_i_change && found_conflict) {
                    ntrigger_attempts++;
                    should_change = true;

                    // CRITICAL FIX: Exclude current type
                    double r = random.uniform();
                    if (my_eff_type == 3) {
                        new_type = (r < 0.5) ? 4 : 5;
                    } else if (my_eff_type == 4) {
                        new_type = (r < 0.5) ? 3 : 5;
                    } else if (my_eff_type == 5) {
                        new_type = (r < 0.5) ? 3 : 4;
                    } else {
                        // Fallback
                        if (r < 0.333333) new_type = 3;
                        else if (r < 0.666666) new_type = 4;
                        else new_type = 5;
                    }

                    nattempts++;
                    int jitter_magnitude = 10;
                    int random_jitter = static_cast<int>(random.uniform() * jitter_magnitude);
                    contact_timer[i] = -random_jitter;
                }
            }
        }
    }

    if (should_change) {
        mol_changes[molecule[i]] = new_type;
    }

    prev_coord[i] = total_coord;
  }

  // GLOBAL RATE LIMITER
  int local_change_count = static_cast<int>(mol_changes.size());
  int total_changes_global = 0;
  MPI_Allreduce(&local_change_count, &total_changes_global, 1, MPI_INT, MPI_SUM, world);

  if (total_changes_global > parameter.max_changes_per_step) {
      int rate_limiter_seed = seed + static_cast<int>(timestep) + comm->me + 7777;
      RanPark rate_limiter_random(lmp, rate_limiter_seed);

      double reduction_factor = static_cast<double>(parameter.max_changes_per_step) / static_cast<double>(total_changes_global);
      int allowed_local = static_cast<int>(local_change_count * reduction_factor + 0.5);
      if (allowed_local > local_change_count) allowed_local = local_change_count;
      if (allowed_local < 0) allowed_local = 0;

      if (allowed_local < local_change_count) {
          std::vector<int> mol_ids;
          for (const auto& pair : mol_changes) {
              mol_ids.push_back(pair.first);
          }

          for (size_t i = 0; i < mol_ids.size(); i++) {
              size_t j = static_cast<size_t>(rate_limiter_random.uniform() * (mol_ids.size() - i)) + i;
              std::swap(mol_ids[i], mol_ids[j]);
          }

          std::map<int, int> limited_mol_changes;
          for (int i = 0; i < allowed_local && i < static_cast<int>(mol_ids.size()); i++) {
              limited_mol_changes[mol_ids[i]] = mol_changes[mol_ids[i]];
          }
          mol_changes = limited_mol_changes;
      }
  }

  // UPDATE LOOP
  std::map<int, int> mol_cooldown_durations;
  if (!mol_changes.empty()) {
      int update_seed = seed + static_cast<int>(timestep) + comm->me + 9999;
      RanPark update_random(lmp, update_seed);

      for (const auto& pair : mol_changes) {
          int mol_id = pair.first;
          double cooldown_factor = 0.3 + update_random.uniform() * 1.7;
          mol_cooldown_durations[mol_id] = static_cast<int>(10000 * cooldown_factor);
      }

      for (int i = 0; i < nlocal; i++) {
          auto it = mol_changes.find(molecule[i]);
          if (it != mol_changes.end()) {
              effective_type[i] = it->second;
              last_change[i] = timestep;
              cooldown_duration[i] = mol_cooldown_durations[molecule[i]];

              int jitter_magnitude = 10;
              int mol_id = molecule[i];
              int timer_seed = seed + static_cast<int>(timestep) + comm->me + mol_id + 8888;
              RanPark timer_random(lmp, timer_seed);
              int random_jitter = static_cast<int>(timer_random.uniform() * jitter_magnitude);
              contact_timer[i] = -random_jitter;
              nchanges++;
          }
      }
  }

  comm->forward_comm(this);

  // Consistency sweep (if enabled)
  {
    int nall = atom->nlocal + atom->nghost;
    std::map<int, int> best_type_per_mol;
    std::map<int, bigint> newest_time_per_mol;

    for (int i = 0; i < nall; i++) {
        if (molecule[i] <= 0) continue;
        if (type[i] < 2 || type[i] > 5) continue;
        if (last_change[i] < 0) continue;
        if (last_change[i] > timestep) continue;

        int mol_id = molecule[i];
        if (newest_time_per_mol.find(mol_id) == newest_time_per_mol.end() ||
            last_change[i] > newest_time_per_mol[mol_id]) {
            newest_time_per_mol[mol_id] = last_change[i];
            best_type_per_mol[mol_id] = effective_type[i];
        }
    }

    for (int i = 0; i < nlocal; i++) {
        if (molecule[i] <= 0) continue;
        if (type[i] < 2 || type[i] > 5) continue;

        int mol_id = molecule[i];
        if (best_type_per_mol.find(mol_id) != best_type_per_mol.end()) {
            int target_type = best_type_per_mol[mol_id];

            bool in_cooldown = false;
            if (last_change[i] >= 0) {
                bigint steps_since_change = timestep - last_change[i];
                if (steps_since_change < cooldown_duration[i]) {
                    in_cooldown = true;
                }
            }

            bool target_is_significantly_newer = false;
            bigint target_timestamp = newest_time_per_mol[mol_id];
            if (last_change[i] < 0) {
                target_is_significantly_newer = true;
            } else {
                if (target_timestamp > timestep) {
                    target_is_significantly_newer = false;
                } else {
                    bigint timestamp_diff = target_timestamp - last_change[i];
                    if (timestamp_diff > 100) {
                        target_is_significantly_newer = true;
                    }
                }
            }

            if (!in_cooldown && target_is_significantly_newer && effective_type[i] != target_type) {
                effective_type[i] = target_type;
                last_change[i] = timestep;
            }
        }
    }
  }

  comm->forward_comm(this);
  MPI_Allreduce(MPI_IN_PLACE, &nchanges, 1, MPI_INT, MPI_SUM, world);
}

void FixStateChangeOctahedronAvoidSameTypeOctahedron::update_atom_types()
{
  bigint natoms_before = atom->natoms;
  comm->forward_comm(this);

  int *type = atom->type;
  int *mask = atom->mask;
  int *molecule = atom->molecule;
  int nlocal = atom->nlocal;

  for (int i = 0; i < nlocal; i++) {
    if (!(mask[i] & groupbit)) continue;
    if (!(mask[i] & group->bitmask[group_patches])) continue;
    if (type[i] != 2 && type[i] != 3 && type[i] != 4 && type[i] != 5) continue;

    int eff = effective_type[i];
    int new_lammps_type;

    if (eff == 1) {
      new_lammps_type = 2;
    } else if (eff == 3 || eff == 4 || eff == 5) {
      new_lammps_type = eff;
    } else {
      continue;
    }

    if (type[i] != new_lammps_type) {
      type[i] = new_lammps_type;
    }
  }

  if (atom->natoms != natoms_before) {
    error->all(FLERR, "Fix fix_state_change_octahedron_avoid_same_type_octahedron: Atom count changed during type update");
  }

  comm->forward_comm();

  if (atom->natoms != natoms_before) {
    error->all(FLERR, "Fix fix_state_change_octahedron_avoid_same_type_octahedron: Atom count changed after communication");
  }

  neighbor->decide();
}

double FixStateChangeOctahedronAvoidSameTypeOctahedron::compute_scalar()
{
  return static_cast<double>(nchanges);
}

void FixStateChangeOctahedronAvoidSameTypeOctahedron::grow_arrays(int nmax)
{
  memory->grow(last_change, nmax, "fix_state_change_octahedron_avoid_same_type_octahedron:last_change");
  memory->grow(cooldown_duration, nmax, "fix_state_change_octahedron_avoid_same_type_octahedron:cooldown_duration");
  memory->grow(effective_type, nmax, "fix_state_change_octahedron_avoid_same_type_octahedron:effective_type");
  memory->grow(prev_coord, nmax, "fix_state_change_octahedron_avoid_same_type_octahedron:prev_coord");
  memory->grow(contact_timer, nmax, "fix_state_change_octahedron_avoid_same_type_octahedron:contact_timer");
}

void FixStateChangeOctahedronAvoidSameTypeOctahedron::copy_arrays(int i, int j, int /*delflag*/)
{
  last_change[j] = last_change[i];
  cooldown_duration[j] = cooldown_duration[i];
  effective_type[j] = effective_type[i];
  prev_coord[j] = prev_coord[i];
  contact_timer[j] = contact_timer[i];
}

int FixStateChangeOctahedronAvoidSameTypeOctahedron::pack_forward_comm(int n, int *list, double *buf, int pbc_flag, int *pbc)
{
  int i, j, m = 0;

  for (i = 0; i < n; i++) {
    j = list[i];
    buf[m++] = static_cast<double>(last_change[j]);
    buf[m++] = static_cast<double>(cooldown_duration[j]);
    buf[m++] = static_cast<double>(effective_type[j]);
    buf[m++] = prev_coord[j];
  }

  return m;
}

void FixStateChangeOctahedronAvoidSameTypeOctahedron::unpack_forward_comm(int n, int first, double *buf)
{
  int i, m = 0, last = first + n;

  for (i = first; i < last; i++) {
    last_change[i] = static_cast<int>(buf[m++]);
    cooldown_duration[i] = static_cast<int>(buf[m++]);
    effective_type[i] = static_cast<int>(buf[m++]);
    prev_coord[i] = buf[m++];
  }
}
