#!/usr/bin/env python3
"""
Extract submissions from Google Sheets CSV export.

Automatically tracks which rows have been processed and only extracts new ones.

Usage:
    # 1. Export Google Sheet as CSV (File → Download → CSV)
    # 2. Run script:
    python3 tools/extract_from_sheets.py responses.csv problem-001-dimer-ksat

    # Only new submissions since last run will be extracted!

Features:
    - Tracks processed rows in .processed_rows.json
    - Skips already-extracted submissions automatically
    - Validates JSON before extraction
    - Progress reporting
"""

import argparse
import csv
import json
import sys
from pathlib import Path
from datetime import datetime
from typing import Set, List, Dict, Any

# Configuration
PRIVATE_REPO = Path.home() / 'lammps-state-change-private'
INBOX_DIR = PRIVATE_REPO / 'submissions-inbox'
TRACKING_DIR = PRIVATE_REPO / '.sheets-tracking'


def load_processed_rows(sheet_name: str) -> Set[int]:
    """Load set of already-processed row numbers."""
    TRACKING_DIR.mkdir(parents=True, exist_ok=True)
    tracking_file = TRACKING_DIR / f'{sheet_name}.json'

    if tracking_file.exists():
        with open(tracking_file) as f:
            data = json.load(f)
            return set(data.get('processed_rows', []))
    return set()


def save_processed_rows(sheet_name: str, processed_rows: Set[int]):
    """Save set of processed row numbers."""
    TRACKING_DIR.mkdir(parents=True, exist_ok=True)
    tracking_file = TRACKING_DIR / f'{sheet_name}.json'

    data = {
        'processed_rows': sorted(list(processed_rows)),
        'last_updated': datetime.now().isoformat()
    }

    with open(tracking_file, 'w') as f:
        json.dump(data, f, indent=2)


def validate_json_string(json_str: str, field_name: str) -> bool:
    """Check if string is valid JSON."""
    try:
        json.loads(json_str)
        return True
    except json.JSONDecodeError as e:
        print(f"  ✗ Invalid JSON in {field_name}: {e}")
        return False


def extract_submission(row: Dict[str, str], row_num: int, problem_id: str) -> bool:
    """
    Extract a single submission from CSV row.

    Expected columns:
        - Timestamp (auto-generated by Google Forms)
        - Username
        - Problem ID
        - policy.json (full JSON content)
        - params.json (optional, full JSON content)

    Returns:
        True if extraction succeeded, False otherwise
    """

    # Extract fields (adjust column names to match your Google Form)
    try:
        username = row.get('Username', row.get('username', '')).strip()
        problem_id_from_form = row.get('Problem ID', row.get('problem_id', problem_id)).strip()
        policy_json_str = row.get('policy.json', row.get('Policy JSON', '')).strip()
        params_json_str = row.get('params.json', row.get('Parameters JSON', '')).strip()
        email = row.get('Email', row.get('email', '')).strip()
        timestamp = row.get('Timestamp', datetime.now().isoformat())

    except Exception as e:
        print(f"  ✗ Row {row_num}: Error reading fields: {e}")
        return False

    # Validate required fields
    if not username:
        print(f"  ✗ Row {row_num}: Missing username")
        return False

    if not policy_json_str:
        print(f"  ✗ Row {row_num}: Missing policy.json")
        return False

    # Validate JSON syntax
    if not validate_json_string(policy_json_str, 'policy.json'):
        print(f"  ✗ Row {row_num}: Invalid policy.json")
        return False

    if params_json_str and not validate_json_string(params_json_str, 'params.json'):
        print(f"  ✗ Row {row_num}: Invalid params.json")
        return False

    # Create destination directory
    dest_dir = INBOX_DIR / f"{username}_{problem_id}"
    dest_dir.mkdir(parents=True, exist_ok=True)

    # Write policy.json
    try:
        policy_data = json.loads(policy_json_str)
        with open(dest_dir / 'policy.json', 'w') as f:
            json.dump(policy_data, f, indent=2)
    except Exception as e:
        print(f"  ✗ Row {row_num}: Error writing policy.json: {e}")
        return False

    # Write params.json if provided
    if params_json_str:
        try:
            params_data = json.loads(params_json_str)
            with open(dest_dir / 'params.json', 'w') as f:
                json.dump(params_data, f, indent=2)
        except Exception as e:
            print(f"  ✗ Row {row_num}: Error writing params.json: {e}")
            return False

    # Create submission.json
    submission_data = {
        'problem_id': problem_id,
        'username': username,
        'timestamp': timestamp,
        'submission_method': 'google_sheets',
        'email': email,
        'sheet_row': row_num
    }

    try:
        with open(dest_dir / 'submission.json', 'w') as f:
            json.dump(submission_data, f, indent=2)
    except Exception as e:
        print(f"  ✗ Row {row_num}: Error writing submission.json: {e}")
        return False

    print(f"  ✓ Row {row_num}: {username} → {dest_dir}")
    return True


def main():
    parser = argparse.ArgumentParser(
        description='Extract submissions from Google Sheets CSV export',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example workflow:
  1. Export Google Sheet as CSV (File → Download → CSV)
  2. Run: python3 tools/extract_from_sheets.py responses.csv problem-001-dimer-ksat
  3. Only NEW rows since last run will be extracted
  4. Run: tools/workflow process-new problem-001-dimer-ksat

Column names (must match your Google Form):
  - Timestamp (auto-generated)
  - Username (required)
  - Problem ID (optional if specified in command)
  - policy.json (required - full JSON content)
  - params.json (optional - full JSON content)
  - Email (optional)
        """
    )

    parser.add_argument('csv_file', help='Path to CSV file exported from Google Sheets')
    parser.add_argument('problem_id', help='Problem ID (e.g., problem-001-dimer-ksat)')
    parser.add_argument('--force', action='store_true', help='Reprocess all rows (ignore tracking)')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be extracted without doing it')

    args = parser.parse_args()

    csv_path = Path(args.csv_file)

    if not csv_path.exists():
        print(f"Error: CSV file not found: {csv_path}")
        sys.exit(1)

    # Load tracking data
    sheet_name = csv_path.stem
    processed_rows = set() if args.force else load_processed_rows(sheet_name)

    print("=" * 80)
    print("  Extract from Google Sheets")
    print("=" * 80)
    print(f"  CSV file: {csv_path}")
    print(f"  Problem:  {args.problem_id}")
    print(f"  Already processed: {len(processed_rows)} rows")
    if args.dry_run:
        print("  Mode: DRY RUN (no files will be created)")
    print()

    # Read CSV
    try:
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            rows = list(reader)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        sys.exit(1)

    if not rows:
        print("No rows found in CSV")
        sys.exit(0)

    print(f"Total rows in CSV: {len(rows)}")
    print()

    # Process new rows
    new_rows = []
    success_count = 0
    fail_count = 0

    for idx, row in enumerate(rows, start=2):  # Start at 2 (1 is header)
        if idx in processed_rows and not args.force:
            continue  # Skip already processed

        new_rows.append((idx, row))

    if not new_rows:
        print("✓ No new submissions to process")
        print()
        return

    print(f"Processing {len(new_rows)} new rows...")
    print()

    for row_num, row in new_rows:
        if args.dry_run:
            username = row.get('Username', row.get('username', 'unknown'))
            print(f"  Would extract row {row_num}: {username}")
            success_count += 1
        else:
            if extract_submission(row, row_num, args.problem_id):
                processed_rows.add(row_num)
                success_count += 1
            else:
                fail_count += 1

    print()
    print("=" * 80)
    print("  Summary")
    print("=" * 80)
    print(f"  New rows:     {len(new_rows)}")
    print(f"  Extracted:    {success_count}")
    print(f"  Failed:       {fail_count}")
    print()

    # Save tracking data
    if not args.dry_run and success_count > 0:
        save_processed_rows(sheet_name, processed_rows)
        print(f"✓ Tracking saved: {len(processed_rows)} total rows processed")
        print()
        print("Next steps:")
        print(f"  1. Check status:     tools/workflow status {args.problem_id}")
        print(f"  2. Process new only: tools/workflow process-new {args.problem_id} -j 4")
    elif args.dry_run:
        print("Dry run complete - no files created")

    print()


if __name__ == '__main__':
    main()
