#!/usr/bin/env python3
"""
Generate LAMMPS C++ fix from declarative JSON policy.

This generator translates user-defined state transition policies into
optimized C++ LAMMPS fixes, implementing the π(j|s,H) policy function
from the molecular computing framework.

Usage:
    python generate_fix_from_policy.py policy.json output_dir/
"""

import json
import sys
import os
from pathlib import Path
from typing import Dict, List, Any

try:
    import jsonschema
    HAS_JSONSCHEMA = True
except ImportError:
    HAS_JSONSCHEMA = False
    print("Warning: jsonschema not installed, skipping validation")


def validate_policy(policy: Dict[str, Any], schema_path: str) -> None:
    """Validate policy against JSON schema."""
    if not HAS_JSONSCHEMA:
        print("⚠ Skipping validation (install jsonschema for validation)")
        return

    with open(schema_path) as f:
        schema = json.load(f)
    jsonschema.validate(instance=policy, schema=schema)
    print(f"✓ Policy validation passed")


def generate_fix_header(policy: Dict[str, Any], fix_name: str) -> str:
    """Generate .h header file."""

    header = f"""/* -*- c++ -*- ----------------------------------------------------------
   LAMMPS fix for state-change policy: {policy['policy_name']}
   Auto-generated from JSON policy specification
   Version: {policy['policy_version']}

   Policy Description:
   {policy.get('description', 'No description provided')}

   DO NOT EDIT THIS FILE MANUALLY - regenerate from policy.json
------------------------------------------------------------------------- */

#ifdef FIX_CLASS
FixStyle(state/change/{fix_name}, FixStateChange{fix_name.title().replace('_', '')})
#else

#ifndef LMP_FIX_STATE_CHANGE_{fix_name.upper()}_H
#define LMP_FIX_STATE_CHANGE_{fix_name.upper()}_H

#include "fix.h"

namespace LAMMPS_NS {{

class FixStateChange{fix_name.title().replace('_', '')} : public Fix {{
 public:
  FixStateChange{fix_name.title().replace('_', '')}(class LAMMPS *, int, char **);
  ~FixStateChange{fix_name.title().replace('_', '')}() override;
  int setmask() override;
  void post_integrate() override;

 private:
  int nevery;           // Check frequency
  int group_patches;    // Group for patch atoms
  class RanPark *random;  // Random number generator

  // Policy-specific parameters
"""

    # Add transition-specific parameters
    for i, trans in enumerate(policy['state_transitions']):
        header += f"  double cutoff_{i};       // Contact cutoff for transition {i}\n"
        header += f"  double cutoffsq_{i};     // Squared cutoff\n"
        header += f"  double pflip_{i};        // Flip probability for transition {i}\n"
        header += f"  int hysteresis_{i};      // Hysteresis checks for transition {i}\n"

    header += """
  // Contact tracking for hysteresis
  int *contact_counter;

  // Detection and flip logic
  void detect_and_schedule(int i, std::vector<int> &mol_list);
};

}

#endif
#endif
"""
    return header


def generate_transition_code(trans: Dict[str, Any], trans_idx: int,
                             species_map: Dict[str, int]) -> str:
    """Generate C++ code for a single state transition rule."""

    from_type = species_map[trans['from_species']]
    to_type = species_map[trans['to_species']]

    trigger = trans['trigger']

    code = f"""
  // Transition {trans_idx}: {trans['from_species']} -> {trans['to_species']}
  // Trigger: {trigger}
  if (type[i] != {from_type}) return;  // Only {trans['from_species']} patches

"""

    if 'contact_required' in trigger:
        contact = trigger['contact_required']
        contact_type = species_map[contact['species']]
        min_contacts = contact['min_contacts']
        logic = contact.get('logic', 'AND')

        if logic == 'NOT' and min_contacts == 0:
            # Contact NOT required (reverse logic)
            code += f"""  // Check for ABSENCE of {contact['species']} contact
  bool found = false;
  for (int j = 0; j < nall; j++) {{
    if (j == i) continue;
    if (!(mask[j] & group->bitmask[group_patches])) continue;
    if (type[j] != {contact_type}) continue;

    double dx = x[j][0] - x[i][0];
    double dy = x[j][1] - x[i][1];
    double dz = x[j][2] - x[i][2];
    if (prd) {{
      if (prd[0] > 0.0) dx -= prd[0] * std::round(dx / prd[0]);
      if (prd[1] > 0.0) dy -= prd[1] * std::round(dy / prd[1]);
      if (prd[2] > 0.0) dz -= prd[2] * std::round(dz / prd[2]);
    }}
    double rsq = dx*dx + dy*dy + dz*dz;
    if (rsq < cutoffsq_{trans_idx}) {{
      found = true;
      break;
    }}
  }}

  // Only flip if NO contact (NOT logic)
  if (!found) {{
    contact_counter[i] += 1;
  }} else {{
    contact_counter[i] = 0;
  }}
"""
        else:
            # Contact required (normal logic)
            code += f"""  // Check for {contact['species']} contact
  bool found = false;
  for (int j = 0; j < nall; j++) {{
    if (j == i) continue;
    if (!(mask[j] & group->bitmask[group_patches])) continue;
    if (type[j] != {contact_type}) continue;

    double dx = x[j][0] - x[i][0];
    double dy = x[j][1] - x[i][1];
    double dz = x[j][2] - x[i][2];
    if (prd) {{
      if (prd[0] > 0.0) dx -= prd[0] * std::round(dx / prd[0]);
      if (prd[1] > 0.0) dy -= prd[1] * std::round(dy / prd[1]);
      if (prd[2] > 0.0) dz -= prd[2] * std::round(dz / prd[2]);
    }}
    double rsq = dx*dx + dy*dy + dz*dz;
    if (rsq < cutoffsq_{trans_idx}) {{
      found = true;
      break;
    }}
  }}

  if (found) {{
    contact_counter[i] += 1;
  }} else {{
    contact_counter[i] = 0;
  }}
"""

    code += f"""
  // Schedule flip if hysteresis threshold met
  if (contact_counter && contact_counter[i] >= hysteresis_{trans_idx}) {{
    int mol = molecule[i];
    if (mol > 0) mol_list.push_back(mol);
    contact_counter[i] = 0;  // Reset
  }}
"""

    return code


def generate_fix_cpp(policy: Dict[str, Any], fix_name: str,
                     species_map: Dict[str, int]) -> str:
    """Generate .cpp implementation file."""

    class_name = f"FixStateChange{fix_name.title().replace('_', '')}"

    cpp = f"""/* ----------------------------------------------------------------------
   LAMMPS fix for state-change policy: {policy['policy_name']}
   Auto-generated from JSON policy specification

   Policy: {policy.get('description', 'No description')}

   DO NOT EDIT THIS FILE MANUALLY - regenerate from policy.json
------------------------------------------------------------------------- */

#include "fix_state_change_{fix_name}.h"

#include "atom.h"
#include "comm.h"
#include "domain.h"
#include "error.h"
#include "group.h"
#include "memory.h"
#include "random_park.h"
#include "update.h"

#include <cmath>
#include <cstdio>
#include <set>
#include <vector>

using namespace LAMMPS_NS;
using namespace FixConst;

{class_name}::{class_name}(LAMMPS *lmp, int narg, char **arg)
    : Fix(lmp, narg, arg), contact_counter(nullptr), random(nullptr) {{

  if (narg < 5)
    error->all(FLERR, "Illegal fix state/change/{fix_name} command");

  nevery = {policy['check_frequency']};

  group_patches = group->find(arg[3]);
  if (group_patches < 0)
    error->all(FLERR, "Fix state/change/{fix_name}: group not found");

"""

    # Initialize transition parameters
    for i, trans in enumerate(policy['state_transitions']):
        trigger = trans['trigger']
        if 'contact_required' in trigger:
            cutoff = trigger['contact_required']['cutoff']
            cpp += f"  cutoff_{i} = {cutoff};\n"
            cpp += f"  cutoffsq_{i} = {cutoff} * {cutoff};\n"
        cpp += f"  pflip_{i} = {trans['flip_probability']};\n"
        cpp += f"  hysteresis_{i} = {trans.get('hysteresis_checks', 1)};\n"

    seed = policy.get('advanced', {}).get('random_seed', 12345)
    cpp += f"""
  random = new RanPark(lmp, {seed});

  memory->create(contact_counter, atom->nmax, "state/change/{fix_name}:contact_counter");
  for (int i = 0; i < atom->nmax; i++) contact_counter[i] = 0;
}}

{class_name}::~{class_name}() {{
  delete random;
  memory->destroy(contact_counter);
}}

int {class_name}::setmask() {{
  int mask = 0;
  mask |= POST_INTEGRATE;
  return mask;
}}

void {class_name}::detect_and_schedule(int i, std::vector<int> &mol_list) {{
  int *type = atom->type;
  int *mask = atom->mask;
  int *molecule = atom->molecule;
  int nall = atom->nlocal + atom->nghost;
  double **x = atom->x;
  double *prd = domain->prd;

  if (!(mask[i] & group->bitmask[group_patches])) return;

  // Check each transition rule
"""

    # Generate detection code for each transition
    for i, trans in enumerate(policy['state_transitions']):
        cpp += generate_transition_code(trans, i, species_map)

    cpp += """}

void """ + class_name + """::post_integrate() {
  if (update->ntimestep % nevery) return;

  int nlocal = atom->nlocal;
  int *molecule = atom->molecule;
  int *type = atom->type;
  int *mask = atom->mask;

  std::vector<int> to_flip;
  to_flip.reserve(64);

  for (int i = 0; i < nlocal; i++) {
    detect_and_schedule(i, to_flip);
  }

  if (to_flip.empty()) return;

  std::set<int> unique_mols(to_flip.begin(), to_flip.end());

  // Apply flips
  for (int mol : unique_mols) {
"""

    # Generate flip application code for each transition
    for i, trans in enumerate(policy['state_transitions']):
        from_type = species_map[trans['from_species']]
        to_type = species_map[trans['to_species']]

        cpp += f"""
    // Transition {i}: {trans['from_species']} -> {trans['to_species']}
    if (random->uniform() <= pflip_{i}) {{
      for (int j = 0; j < nlocal; j++) {{
        if (molecule[j] != mol) continue;
        if (!(mask[j] & group->bitmask[group_patches])) continue;
        if (type[j] == {from_type}) {{
          type[j] = {to_type};
          if (comm->me == 0) {{
            fprintf(stderr, "STATECHANGE {fix_name}: step %ld mol %d flipped {trans['from_species']}->{trans['to_species']}\\n",
                    update->ntimestep, mol);
          }}
        }}
      }}
    }}
"""

    cpp += """  }
}
"""

    return cpp


def main():
    if len(sys.argv) < 3:
        print("Usage: python generate_fix_from_policy.py policy.json output_dir/")
        sys.exit(1)

    policy_path = sys.argv[1]
    output_dir = Path(sys.argv[2])

    # Load policy
    with open(policy_path) as f:
        policy = json.load(f)

    # Validate against schema
    schema_path = Path(__file__).parent.parent / "schemas" / "policy_schema.json"
    validate_policy(policy, str(schema_path))

    # Extract fix name from policy
    fix_name = policy['policy_name'].lower().replace(' ', '_').replace('-', '_')

    # Build species mapping (from problem.json - for now hardcode dimer_ksat)
    # TODO: Load from problem.json
    species_map = {
        'core': 1,
        'A': 2,
        'B': 3,
        'C': 4
    }

    # Generate files
    output_dir.mkdir(parents=True, exist_ok=True)

    header_code = generate_fix_header(policy, fix_name)
    cpp_code = generate_fix_cpp(policy, fix_name, species_map)

    header_path = output_dir / f"fix_state_change_{fix_name}.h"
    cpp_path = output_dir / f"fix_state_change_{fix_name}.cpp"

    with open(header_path, 'w') as f:
        f.write(header_code)

    with open(cpp_path, 'w') as f:
        f.write(cpp_code)

    print(f"✓ Generated {header_path}")
    print(f"✓ Generated {cpp_path}")
    print(f"\nNext steps:")
    print(f"  1. Copy files to LAMMPS src/ directory")
    print(f"  2. Recompile LAMMPS")
    print(f"  3. Use in LAMMPS script: fix ID group state/change/{fix_name} ...")


if __name__ == "__main__":
    main()
